### ISSUE TITLE
why scanning?

### ISSUE THREAD

**Issue by tcurdt** [marcello3d/node-mongolian#36]
Although mongolian gets passed in the connection information

```
var mongo = new Mongolian('localhost:27017');
```

it prints

```
mongo://localhost:27017: Connected
mongo://localhost:27017: Initialized as primary
mongo://localhost:27017: Connected to primary
Finished scanning... primary? mongo://localhost:27017
```

which suggests it's searching for mongo. Why the scanning?

**Comment by marcello3d** [comment]
The scanning process is to handle replica sets (
http://www.mongodb.org/display/DOCS/Replica+Sets).

Mongolian DB will connect to the specified mongo server(s), ask them if
they're a primary server (and potentially learn about new servers), and
finally settle on the primary server (if found).

In a single-server setup, this process is pretty simple and fast since there
is only one server and it's always the primary server. These messages are
most useful for debugging complex setups.

**Comment by tcurdt** [comment]
shouldn't the messages only be printed when debugging, then?

**Comment by marcello3d** [comment]
It's the default console logging. There's no standard node.js "debugging" mode that is appropriate here, so if you want to change the logging style, pass a custom logger into the constructor as described in the readme.

**Comment by tcurdt** [comment]
"debugging" in the sense of "I need that kind of information and for that reason set a custom logger".
