### ISSUE TITLE
forEach is nesting?

### ISSUE THREAD

**Issue by bingomanatee** [marcello3d/node-mongolian#46]
var mm = require(MVC_MODELS);

module.exports.run = function() {
    mm.model('mapimage_tile', function(err, mit_model) {
        var tile_list = [];
        var cursor = mit_model.find({}, {heights: 0});

```
    function _process_tile(tile){
       console.log('tile', tile._id, 'r', tile.tile_i, 'c', tile.tile_j);
    }

    function _done(){
        console.log('------- done ------');
    }
    cursor.forEach(_process_tile, _done);
});
```

}

for a very large collection returns the error: 

console.js:40
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
RangeError: Maximum call stack size exceeded

Seems to me the call stack should be fairly flat shouldn't it? This might not be a mongolian error, but I thought I'd bring it to your attention anyway.

**Comment by marcello3d** [comment]
This almost looks like it might be a node.js bug triggered by the console.log (considering the range error happens in console.js). What happens if you replace the _process_tile log method with some static console.log('foo') line?

I think Mongolian DB will do some slightly deep stacks (hardly uncommon in a functional language), but it should be a constant depth depending on the batch size mongodb returns. You could test this with console.trace().

**Comment by marcello3d** [comment]
Ok, I was able to reproduce this bug in nithub. I have a fix to flatten forEach and it should run more optimally.
